### PR TITLE
Asynchronous table load for articles, _history fix

### LINKED ISSUE #166: History page error
http://flat.nert.georgetown.edu/en/streusle4.1/_history/ (from clicking "Changes" on http://flat.nert.georgetown.edu/en/streusle4.1/) gives an Internal Server Error

### PR DESCRIPTION
**Pull request by lgessler**
Fixes #166, #169, #170

### CODE REVIEW

**Comment by nschneid** [comment]
Nice! For #169 would it be easy to implement loading more on demand as the user scrolls down or should we keep the pagination?

**Comment by lgessler** [comment]
I feel that interaction would take some fiddling to implement right, esp. since there's an embedded vertical scroll. I think pagination is safer unless we really feel a need for that infinite scroll–style interaction.

**Comment by nschneid** [comment]
OK. If the user really wants to see a lot of examples they should open in a new window.

**Comment by lgessler** [comment]
Yeah, in fact, I just changed the code so they have to open a new window if they want to see more than 25. It's really doing them a favor, scrolling down to the end of the page after every round trip isn't good.

**Pull request merged**
