### PR TITLE
Tweak import code for PASTRIE

### PR DESCRIPTION
**Pull request by lgessler**
~Two~ One change:
- ~tolerate preps without ss annotation (a few still remain in the corpus)~
- tolerate no govobj information

### CODE REVIEW

**Comment by nschneid** [comment]
What are the preps without ss annotation?

**Comment by lgessler** [comment]
line nos are for: https://github.com/nitinvwaran/pastrie/blob/master/corpus_enriched.conllulex

```
L2500 (spanish-022ee17b-a59d-43d6-65c9-90b2acb26b87-11, token 23): untagged prep
L4639 (english-120961ea-0913-5087-15d3-8ca9986cc8d5-05, token 7): untagged prep
L6336 (spanish-1d76d7a0-219d-c07b-1abf-286b47e0643b-01, token 1): untagged prep
L8992 (german-8ebdbfe3-eb9a-c688-b9d3-9cca91551e82-04, token 16): untagged prep
L9029 (german-8ebdbfe3-eb9a-c688-b9d3-9cca91551e82-07, token 21): untagged prep
L10588 (english-38553ac8-7d71-8591-3fee-2fc72e2dffdf-03, token 13): untagged prep
L12338 (german-7d8dd474-c146-a389-381b-37241398aa12-02, token 1): untagged prep
L12916 (spanish-c55fd024-99dd-8bfa-b3d7-77e95bc2b64f-01, token 1): untagged prep
L12947 (spanish-c55fd024-99dd-8bfa-b3d7-77e95bc2b64f-01, token 32): untagged prep
L13022 (spanish-c55fd024-99dd-8bfa-b3d7-77e95bc2b64f-05, token 10): untagged prep
L13064 (spanish-c55fd024-99dd-8bfa-b3d7-77e95bc2b64f-06, token 26): untagged prep
L13761 (french-6e671698-1e83-0596-3646-9fabf59cd100-03, token 7): untagged prep
L16439 (german-c2b1c26b-e814-7dc9-af47-9f2936631b3e-03, token 1): untagged prep
L19921 (german-a40837a9-f5ce-a353-e90e-2383743444ab-02, token 2): untagged prep
L24756 (german-a71d226c-2c56-a0ee-64be-9726fc430932-04, token 4): untagged prep
```

**Comment by nschneid** [comment]
Thanks. Shouldn't these receive a **special label** (e.g. `` `d``) in Xposition? Or does the import code not handle these tokens?

**Comment by lgessler** [comment]
Is it Xposition or the scripts that prepare the corpus (up to and including the .json output) that is responsible for adding labels like `d? I don't think the import code makes changes to the data like that, if that's what you're asking?

**Comment by nschneid** [comment]
Those ones look like intransitive verb particles. Is it expecting govobj info for those?

**Comment by nschneid** [comment]
And does govobj.py not work on the PASTRIE JSON for some reason?

**Comment by lgessler** [comment]
re: the latter, govobj.py requires edeps, which pastrie doesn't have:

```
» python govobj.py ~/local/nert/pastrie.json                                                                                                                                                                                                   1 ↵
Traceback (most recent call last):
  File "govobj.py", line 267, in <module>
    enhance(sent)   # apply Enhanced Dependencies instead of superficial conj relations for coordination
  File "govobj.py", line 88, in enhance
    assert tok['edeps']
AssertionError
```

**Comment by nschneid** [comment]
Actually you can probably just comment out [govobj.py line 267](https://github.com/nert-nlp/streusle/blob/98f6d8398727ee5e85e187c3c261827ed91c4fb1/govobj.py#L267) for now. It looks like it only affects coordination constructions.

**Comment by lgessler** [comment]
OK, govobj is able to run without errors with that line commented out, though this does not resolve the issue of the null supersense instances above

**Comment by nschneid** [comment]
Most of the ones listed above ("off", "out", "up") are idiomatic verb particles so they should form strong MWEs. The real question is why the validation script isn't complaining about them.

"give up on" should probably be give_up on/Theme. In corpus.conllulex it's give_up_on/Theme, which doesn't make any sense and in fact should be a validation error because Theme is a SNACS supersense but give_up_on is a verbal rather than prepositional expression.

**Comment by lgessler** [comment]
OK, I think that was getting past the validator because of some bad changes I made to the validator. The diff is now minimal: it doesn't check for `V` subtyping, and it doesn't expect SS annos on N and V anymore (I also made the N and V ss sets empty like you suggested--see commit: https://github.com/nitinvwaran/pastrie/commit/c723866606f2956d841fb28e664db63c075318c6)

```
102,104c102,103
<             # change for PASTRIE--don't check lexcat
<             #if lc=='V':
<             #    assert len(lexe['toknums'])==1,f'In {sent["sent_id"]}, Verbal MWE "{lexe["lexlemma"]}" lexcat must be subtyped (V.VID, etc., not V)'
---
>             if lc=='V':
>                 assert len(lexe['toknums'])==1,f'In {sent["sent_id"]}, Verbal MWE "{lexe["lexlemma"]}" lexcat must be subtyped (V.VID, etc., not V)'
127c124
<                 assert ss is None and ss2 is None and lc not in ('P', 'INF.P', 'PP', 'POSS', 'PRON.POSS'),f"In {sent['sent_id']}, invalid supersense(s) in lexical entry: {lexe}"
---
>                 assert ss is None and ss2 is None and lc not in ('N', 'V', 'P', 'INF.P', 'PP', 'POSS', 'PRON.POSS'),f"In {sent['sent_id']}, invalid supersense(s) in lexical entry: {lexe}"
```

Now the validator properly complains.

**Comment by nschneid** [comment]
Good. In enrich.py maybe implement a rule to add verb+particle MWEs when there is no supersense on "off"/"out"/"up"/"down" and it attaches as compound:prt? The other ones probably require manual review.

**Comment by lgessler** [comment]
@nschneid this is ready for review

**Comment by nschneid** [comment]
Do you still need the fallback conditions for missing govobj? I thought you were able to get govobj to work.

**Comment by lgessler** [comment]
ah that's right, we should be fine now

**Pull request closed without merging**
